version: '2'
services:
  ovn-ctrl:
    image: sunguanke/ovn:v3
    container_name: ovn-master
    hostname: ovn-master
    command: bash -c 'while true; do sleep 10;done'
    privileged: true
    environment: 
      TERM: linux
      MY_IP: 10.10.0.10
    ports:
      - "16640:6640"
      - "16641:6641"
      - "16642:6642"
    networks:
      ovnnet_local:
        ipv4_address: 10.10.0.10
    volumes:
      - ./scripts:/root
  ovn-gateway1:
    image: sunguanke/ovn:v3
    container_name: ovn-gateway1
    hostname: ovn-gateway1
    command: bash -c 'while true; do sleep 10; done'
    privileged: true
    environment: 
      TERM: linux
      OVN_SERVER: 10.10.0.10
      MY_IP: 10.10.0.20
    networks:
      ovnnet_local:
        ipv4_address: 10.10.0.20
      ovnnet_outer:
        ipv4_address: 10.20.0.20
    volumes:
      - ./scripts:/root
  ovn-gateway2:
    image: sunguanke/ovn:v3
    container_name: ovn-gateway2
    hostname: ovn-gateway2
    command: bash -c 'while true; do sleep 10; done'
    privileged: true
    environment: 
      TERM: linux
      OVN_SERVER: 10.10.0.10
      MY_IP: 10.10.0.30
    networks:
      ovnnet_local:
        ipv4_address: 10.10.0.30
      ovnnet_outer:
        ipv4_address: 10.20.0.30
    volumes:
      - ./scripts:/root
  ovn-worker1:
    image: sunguanke/ovn:v3
    container_name: ovn-worker1
    hostname: ovn-worker1
    command: bash -c 'while true; do sleep 10; done'
    privileged: true
    environment: 
      TERM: linux
      OVN_SERVER: 10.10.0.10
      MY_IP: 10.10.0.40
    networks:
      ovnnet_local:
        ipv4_address: 10.10.0.40
      ovnnet_outer:
    volumes:
      - ./scripts:/root
  ovn-worker2:
    image: sunguanke/ovn:v3
    container_name: ovn-worker2
    hostname: ovn-worker2
    command: bash -c 'while true; do sleep 10; done'
    privileged: true
    environment: 
      TERM: linux
      OVN_SERVER: 10.10.0.10
      MY_IP: 10.10.0.50
    networks:
      ovnnet_local:
        ipv4_address: 10.10.0.50
      ovnnet_outer:
    volumes:
      - ./scripts:/root
  ovn-worker3:
    image: sunguanke/ovn:v3
    container_name: ovn-worker3
    hostname: ovn-worker3
    command: bash -c 'while true; do sleep 10; done'
    privileged: true
    environment:
      TERM: linux
      OVN_SERVER: 10.10.0.10
      MY_IP: 10.10.0.51
    networks:
      ovnnet_local:
        ipv4_address: 10.10.0.51
      ovnnet_outer:
    volumes:
      - ./scripts:/root
  ovn-outer:
    image: sunguanke/ovn:v3
    container_name: ovn-outer
    hostname: ovn-outer
    command: bash -c 'while true;do sleep 10;done'
    privileged: true
    environment:
      TERM: linux
      OVN_SERVER: 10.10.0.10
      MY_IP: 10.10.0.60
    ports:
      - "26640:6640"
    networks:
      ovnnet_outer:
    volumes:
      - ./scripts:/root
    

networks:
  ovnnet_local:
    external: true
  ovnnet_outer:
    external: true